apiVersion: apps/v1
kind: Deployment
metadata:
  name: stablediffusiontelegrambot
  labels:
    app: stablediffusiontelegrambot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stablediffusiontelegrambot
  template:
    metadata:
      labels:
        app: stablediffusiontelegrambot
    spec:
      containers:
      - name: stablediffusiontelegrambot
        image: ghcr.io/obviyus/stablediffusiontelegrambot:latest
        env:
        - name: ARCHIVE_CHANNEL_ID
          valueFrom:
            secretKeyRef:
              name: stablediffusiontelegrambot-credentials
              key: ARCHIVE_CHANNEL_ID
        - name: MODAL_TOKEN_ID
          valueFrom:
            secretKeyRef:
              name: stablediffusiontelegrambot-credentials
              key: MODAL_TOKEN_ID
        - name: MODAL_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: stablediffusiontelegrambot-credentials
              key: MODAL_TOKEN_SECRET
        - name: TELEGRAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: stablediffusiontelegrambot-credentials
              key: TELEGRAM_TOKEN
        - name: DATABASE_PATH
          value: "/data/SDTB.db"
        volumeMounts:
        - name: database
          mountPath: /data
      imagePullSecrets:
      - name: ghcr-login-secret
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: sdtb-db-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sdtb-db-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
