apiVersion: apps/v1
kind: Deployment
metadata:
  name: hamverbot
  labels:
    app: hamverbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hamverbot
  template:
    metadata:
      labels:
        app: hamverbot
    spec:
      containers:
      - name: hamverbot
        image: ghcr.io/obviyus/hamverbot:latest
        env:
        - name: RUST_LOG
          value: "info"
        - name: F1_API_KEY
          value: ""
        - name: DATABASE_URL
          value: "sqlite:/data/HamVerBot.db"
        - name: CONFIG_PATH
          value: "/config/config.toml"
        volumeMounts:
        - name: database
          mountPath: /data
        - name: config-volume
          mountPath: /config
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: shared-db-pvc
      - name: config-volume
        configMap:
          name: hamverbot-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hamverbot-config
data:
  config.toml: |
    owners = ['obviyus']
    nickname = "HamVerBot"
    nick_password = "password"
    password = "password"
    realname = "Steward of #f1"
    server = "irc.libera.chat"
    port = 6697
    use_tls = true
    encoding = "UTF-8"
    channels = ["#f1", "#obviyus"]
    umodes = "+RB-x"
    user_info = "IRC bot for #f1"
    version = "irc:git:Rust"
    source = "https://github.com/obviyus/HamVerBot"
    ping_time = 180
    ping_timeout = 20
    burst_window_length = 8
    max_messages_in_burst = 15
    should_ghost = false
    ghost_sequence = []
    [options]
    command_prefix = "!"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-db-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ubuntu/shared-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: shared-db-pv