apiVersion: apps/v1
kind: Deployment
metadata:
  name: superseriousbot
  namespace: superseriousbot
  labels:
    app: superseriousbot
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: superseriousbot
  template:
    metadata:
      labels:
        app: superseriousbot
    spec:
      containers:
        - name: superseriousbot
          image: ghcr.io/obviyus/superseriousbot:latest
          envFrom:
            - secretRef:
                name: superseriousbot-credentials
          env:
            - name: ADMINS
              value: "200482621"
            - name: REDDIT_USER_AGENT
              value: "SuperSeriousBot"
            - name: REDIS_HOST
              value: redis.superseriousbot
            - name: REDIS_PORT
              value: "6379"
            - name: DATABASE_PATH_PREFIX
              value: "/data"
          volumeMounts:
            - name: database
              mountPath: /data
              readOnly: false
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 4Gi
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: ssgbot-db
