apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sherl0ck-db-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sherl0ck
  labels:
    app: sherl0ck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sherl0ck
  template:
    metadata:
      labels:
        app: sherl0ck
    spec:
      containers:
        - name: sherl0ck
          image: ghcr.io/obviyus/sherl0ck
          env:
            - name: DATABASE_PATH
              value: "/data/sherl0ck.db"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: sherl0ck-credentials
                  key: LITESTREAM_ACCESS_KEY_ID        
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: sherl0ck-credentials
                  key: LITESTREAM_SECRET_ACCESS_KEY
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 3000m
              memory: 2Gi
      imagePullSecrets:
        - name: ghcr-login-secret
