---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hamverbot-credentials
  namespace: hamverbot
spec:
  encryptedData:
    f1-api-key: AgAZ2FRVnNDNUzyWrkbID0+dNg9JWOVEA4Zh+Ei3Vae3KK2pSfkW5yN5FzZJjpN/pUx9Avwj3CtvMDGaUnlABvbghGrxSrNm7Vbgl8kLmQ2PitheucIblKp9hF7gyxRU3JKFcamOkZhaTkL1+LO/oLzAlzOjWvcHMoXS//1N1OTsaNidH4xmmNwDB9ySSY8gjb/cIUZOHw14xP0Ylx5zWnYOhnF8ezi+3paO5RkBHzD3rKG8K+DUV1uqdgi3ZqFt4kkVL2T19MnHOUy63C1gCp9woGnsLSvKktOsMJ+yZjSoUprLfToxkXJ713p+UtKwR/rV0oBZ+dDso1+kUDnC88HcamZWvPc3cyeS4Ji59SOLdYWB1ypHHo9sqxlBcpu9VM6jTvSCuSg/Waf08V2+ch+tloNHV1j4EnaH+KA6GHYrFudeFUkpY4iBekNfHBYN3EUi7EvQO3bx6zyHDhbRrFpzhZMf/86RJsmohkUrCuRMcgsCgT6c56tzjXptG48Do41eueqvYhgAWHTEWA1j7CVF5ne7ogcVwxlDoAdujGqJHYHtPowTapgqxLZqbVipDwb0Rn97gW79rmrrCEjiEHf8iOMcaGcnEuHRrXUSvMo7uyR8u0EJuVe1yeH8McCKqO87JJRe6eugrgtYl7pPHCp8rEpdgERBqb6mIBa5UPPR34So+vEVjKL75Xiz4UFsPiRBAynx8lAvrx4aoKz9Mr939/VOzYLv9CDBYxZMHk06Uw==
    irc-password: AgBBxlZhHxYUOE4/M1MfHOVukPPYtNgSMGxwKHb0SX8T3qBrs5dPkjOCPWgqUBVwR/7R3BiPhF+XHisJ4go7Xen88WUo+dO7+6ZSZSyTsA7BFsOsif2eeWBGnpxuEv1TUbK+QceTD7TWMNgUED3f7aK49W0LeIp7rzHoC1PV3hhdjz+Lr3iKSKFBpGXkCxVlL63H2d+O4YYdN0vL/i/kIdZuzxdYvHZJj9xTnZNME13mPNOizciza8O0Cb94JuSQsdnhzdiDgdBZ5WFoR9e1uD3/7Szv0venwqimrDt2kbjK17lcEnRx+kgnXkKbHR6LzRfJ0H6bumMAkRhudETLtweSUXH6IdmABc6Negic5pEUfEut7i1gt75faXNyOqr3WfUsQd1UFkSIKqJsItxSQohkPvLeLLnYywEzrRR6e7hFPgVLYQlslR9OGKjN+6ski/skgmkpWl/5tbHNRP2CUfxTulLc99WVk6nKIDJtxjqfL0Nurak20X7dg4fsRm1g//DIvQ8C2j9rc34TTqVusf1c96NlPYhZc39VSIMr2WUWUkgjcnxNJKZ15sIm2pt5EzOUprE/dCBOBou/cLPrVt8jjz00qXCAYa8jlc0OfV9OTt9sSCVgFG3/UfUQbnytmk+LJTgFLPhE0hRHV1TsZ1jA3hUr9irzTSkFpMYElP/TECERkci1aA/c79plyc9BDI5coR5zLcfRW9mnZQ==
  template:
    metadata:
      creationTimestamp: null
      name: hamverbot-credentials
      namespace: hamverbot
    type: Opaque
