apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-db-pv
spec:
  capacity:
    storage: 1Gi  # Adjust the size as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ubuntu/shared-db  # Path from the host machine
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Should match the size of the PersistentVolume
