apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-default-backend
  namespace: default
  labels:
    app: nginx-default-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-default-backend
  template:
    metadata:
      labels:
        app: nginx-default-backend
    spec:
      containers:
      - name: nginx-default-backend
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-default-backend
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx-default-backend
